# Generated by Django 3.1.4 on 2020-12-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='yearOfPublished',
            field=models.IntegerField(default=False),
        ),
    ]
