# Generated by Django 3.1.4 on 2020-12-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_yearofpublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.IntegerField(default=2020),
        ),
    ]
